version: '3.8'

services:
  secure-web-app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: secure_compliance_app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production